
extension CSSearchableItemAttributeSet {
  var pixelHeight: NSNumber?
  var pixelWidth: NSNumber?
  var pixelCount: NSNumber?
  var colorSpace: String?
  var bitsPerSample: NSNumber?
  var flashOn: NSNumber?
  var focalLength: NSNumber?
  var focalLength35mm: NSNumber?
  var acquisitionMake: String?
  var acquisitionModel: String?
  var cameraOwner: String?
  var lensModel: String?
  var ISOSpeed: NSNumber?
  var orientation: NSNumber?
  var layerNames: [String]?
  var whiteBalance: NSNumber?
  var aperture: NSNumber?
  var profileName: String?
  var resolutionWidthDPI: NSNumber?
  var resolutionHeightDPI: NSNumber?
  var exposureMode: NSNumber?
  var exposureTime: NSNumber?
  var EXIFVersion: String?
  var EXIFGPSVersion: String?
  var hasAlphaChannel: NSNumber?
  var redEyeOn: NSNumber?
  var meteringMode: String?
  var maxAperture: NSNumber?
  var fNumber: NSNumber?
  var exposureProgram: String?
  var exposureTimeString: String?
}
