
protocol CLLocationManagerDelegate : NSObjectProtocol {
  @available(OSX 10.6, *)
  optional func locationManager(manager: CLLocationManager, didUpdateTo newLocation: CLLocation, from oldLocation: CLLocation)
  @available(OSX 10.9, *)
  optional func locationManager(manager: CLLocationManager, didUpdateLocations locations: [AnyObject])
  @available(OSX 10.10, *)
  optional func locationManager(manager: CLLocationManager, didDetermineState state: CLRegionState, for region: CLRegion)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didEnter region: CLRegion)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didExitRegion region: CLRegion)
  @available(OSX 10.6, *)
  optional func locationManager(manager: CLLocationManager, didFailWithError error: NSError)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, monitoringDidFailFor region: CLRegion?, withError error: NSError)
  @available(OSX 10.7, *)
  optional func locationManager(manager: CLLocationManager, didChange status: CLAuthorizationStatus)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didStartMonitoringFor region: CLRegion)
  @available(OSX 10.9, *)
  optional func locationManager(manager: CLLocationManager, didFinishDeferredUpdatesWithError error: NSError?)
}
