
protocol CLLocationManagerDelegate : NSObjectProtocol {
  @available(OSX 10.6, *)
  optional func locationManager(manager: CLLocationManager, didUpdateToLocation newLocation: CLLocation, fromLocation oldLocation: CLLocation)
  @available(OSX 10.9, *)
  optional func locationManager(manager: CLLocationManager, didUpdateLocations locations: [AnyObject])
  @available(OSX 10.10, *)
  optional func locationManager(manager: CLLocationManager, didDetermineState state: CLRegionState, forRegion region: CLRegion)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didEnterRegion region: CLRegion)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didExitRegion region: CLRegion)
  @available(OSX 10.6, *)
  optional func locationManager(manager: CLLocationManager, didFailWithError error: NSError)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, monitoringDidFailForRegion region: CLRegion?, withError error: NSError)
  @available(OSX 10.7, *)
  optional func locationManager(manager: CLLocationManager, didChangeAuthorizationStatus status: CLAuthorizationStatus)
  @available(OSX 10.8, *)
  optional func locationManager(manager: CLLocationManager, didStartMonitoringForRegion region: CLRegion)
  @available(OSX 10.9, *)
  optional func locationManager(manager: CLLocationManager, didFinishDeferredUpdatesWithError error: NSError?)
}
