
@available(OSX 10.7, *)
let metadataItemFSNameKey: String
@available(OSX 10.7, *)
let metadataItemDisplayNameKey: String
@available(OSX 10.7, *)
let metadataItemURLKey: String
@available(OSX 10.7, *)
let metadataItemPathKey: String
@available(OSX 10.7, *)
let metadataItemFSSizeKey: String
@available(OSX 10.7, *)
let metadataItemFSCreationDateKey: String
@available(OSX 10.7, *)
let metadataItemFSContentChangeDateKey: String
@available(OSX 10.9, *)
let metadataItemContentTypeKey: String
@available(OSX 10.9, *)
let metadataItemContentTypeTreeKey: String
@available(OSX 10.7, *)
let metadataItemIsUbiquitousKey: String
@available(OSX 10.7, *)
let metadataUbiquitousItemHasUnresolvedConflictsKey: String
@available(OSX 10.9, *)
let metadataUbiquitousItemDownloadingStatusKey: String
@available(OSX 10.9, *)
let metadataUbiquitousItemDownloadingStatusNotDownloaded: String
@available(OSX 10.9, *)
let metadataUbiquitousItemDownloadingStatusDownloaded: String
@available(OSX 10.9, *)
let metadataUbiquitousItemDownloadingStatusCurrent: String
@available(OSX 10.7, *)
let metadataUbiquitousItemIsDownloadingKey: String
@available(OSX 10.7, *)
let metadataUbiquitousItemIsUploadedKey: String
@available(OSX 10.7, *)
let metadataUbiquitousItemIsUploadingKey: String
@available(OSX 10.7, *)
let metadataUbiquitousItemPercentDownloadedKey: String
@available(OSX 10.7, *)
let metadataUbiquitousItemPercentUploadedKey: String
@available(OSX 10.9, *)
let metadataUbiquitousItemDownloadingErrorKey: String
@available(OSX 10.9, *)
let metadataUbiquitousItemUploadingErrorKey: String
@available(OSX 10.10, *)
let metadataUbiquitousItemDownloadRequestedKey: String
@available(OSX 10.10, *)
let metadataUbiquitousItemIsExternalDocumentKey: String
@available(OSX 10.10, *)
let metadataUbiquitousItemContainerDisplayNameKey: String
@available(OSX 10.10, *)
let metadataUbiquitousItemURLInLocalContainerKey: String
@available(OSX 10.9, *)
let metadataItemAttributeChangeDateKey: String
@available(OSX 10.9, *)
let metadataItemKeywordsKey: String
@available(OSX 10.9, *)
let metadataItemTitleKey: String
@available(OSX 10.9, *)
let metadataItemAuthorsKey: String
@available(OSX 10.9, *)
let metadataItemEditorsKey: String
@available(OSX 10.9, *)
let metadataItemParticipantsKey: String
@available(OSX 10.9, *)
let metadataItemProjectsKey: String
@available(OSX 10.9, *)
let metadataItemDownloadedDateKey: String
@available(OSX 10.9, *)
let metadataItemWhereFromsKey: String
@available(OSX 10.9, *)
let metadataItemCommentKey: String
@available(OSX 10.9, *)
let metadataItemCopyrightKey: String
@available(OSX 10.9, *)
let metadataItemLastUsedDateKey: String
@available(OSX 10.9, *)
let metadataItemContentCreationDateKey: String
@available(OSX 10.9, *)
let metadataItemContentModificationDateKey: String
@available(OSX 10.9, *)
let metadataItemDateAddedKey: String
@available(OSX 10.9, *)
let metadataItemDurationSecondsKey: String
@available(OSX 10.9, *)
let metadataItemContactKeywordsKey: String
@available(OSX 10.9, *)
let metadataItemVersionKey: String
@available(OSX 10.9, *)
let metadataItemPixelHeightKey: String
@available(OSX 10.9, *)
let metadataItemPixelWidthKey: String
@available(OSX 10.9, *)
let metadataItemPixelCountKey: String
@available(OSX 10.9, *)
let metadataItemColorSpaceKey: String
@available(OSX 10.9, *)
let metadataItemBitsPerSampleKey: String
@available(OSX 10.9, *)
let metadataItemFlashOnOffKey: String
@available(OSX 10.9, *)
let metadataItemFocalLengthKey: String
@available(OSX 10.9, *)
let metadataItemAcquisitionMakeKey: String
@available(OSX 10.9, *)
let metadataItemAcquisitionModelKey: String
@available(OSX 10.9, *)
let metadataItemISOSpeedKey: String
@available(OSX 10.9, *)
let metadataItemOrientationKey: String
@available(OSX 10.9, *)
let metadataItemLayerNamesKey: String
@available(OSX 10.9, *)
let metadataItemWhiteBalanceKey: String
@available(OSX 10.9, *)
let metadataItemApertureKey: String
@available(OSX 10.9, *)
let metadataItemProfileNameKey: String
@available(OSX 10.9, *)
let metadataItemResolutionWidthDPIKey: String
@available(OSX 10.9, *)
let metadataItemResolutionHeightDPIKey: String
@available(OSX 10.9, *)
let metadataItemExposureModeKey: String
@available(OSX 10.9, *)
let metadataItemExposureTimeSecondsKey: String
@available(OSX 10.9, *)
let metadataItemEXIFVersionKey: String
@available(OSX 10.9, *)
let metadataItemCameraOwnerKey: String
@available(OSX 10.9, *)
let metadataItemFocalLength35mmKey: String
@available(OSX 10.9, *)
let metadataItemLensModelKey: String
@available(OSX 10.9, *)
let metadataItemEXIFGPSVersionKey: String
@available(OSX 10.9, *)
let metadataItemAltitudeKey: String
@available(OSX 10.9, *)
let metadataItemLatitudeKey: String
@available(OSX 10.9, *)
let metadataItemLongitudeKey: String
@available(OSX 10.9, *)
let metadataItemSpeedKey: String
@available(OSX 10.9, *)
let metadataItemTimestampKey: String
@available(OSX 10.9, *)
let metadataItemGPSTrackKey: String
@available(OSX 10.9, *)
let metadataItemImageDirectionKey: String
@available(OSX 10.9, *)
let metadataItemNamedLocationKey: String
@available(OSX 10.9, *)
let metadataItemGPSStatusKey: String
@available(OSX 10.9, *)
let metadataItemGPSMeasureModeKey: String
@available(OSX 10.9, *)
let metadataItemGPSDOPKey: String
@available(OSX 10.9, *)
let metadataItemGPSMapDatumKey: String
@available(OSX 10.9, *)
let metadataItemGPSDestLatitudeKey: String
@available(OSX 10.9, *)
let metadataItemGPSDestLongitudeKey: String
@available(OSX 10.9, *)
let metadataItemGPSDestBearingKey: String
@available(OSX 10.9, *)
let metadataItemGPSDestDistanceKey: String
@available(OSX 10.9, *)
let metadataItemGPSProcessingMethodKey: String
@available(OSX 10.9, *)
let metadataItemGPSAreaInformationKey: String
@available(OSX 10.9, *)
let metadataItemGPSDateStampKey: String
@available(OSX 10.9, *)
let metadataItemGPSDifferentalKey: String
@available(OSX 10.9, *)
let metadataItemCodecsKey: String
@available(OSX 10.9, *)
let metadataItemMediaTypesKey: String
@available(OSX 10.9, *)
let metadataItemStreamableKey: String
@available(OSX 10.9, *)
let metadataItemTotalBitRateKey: String
@available(OSX 10.9, *)
let metadataItemVideoBitRateKey: String
@available(OSX 10.9, *)
let metadataItemAudioBitRateKey: String
@available(OSX 10.9, *)
let metadataItemDeliveryTypeKey: String
@available(OSX 10.9, *)
let metadataItemAlbumKey: String
@available(OSX 10.9, *)
let metadataItemHasAlphaChannelKey: String
@available(OSX 10.9, *)
let metadataItemRedEyeOnOffKey: String
@available(OSX 10.9, *)
let metadataItemMeteringModeKey: String
@available(OSX 10.9, *)
let metadataItemMaxApertureKey: String
@available(OSX 10.9, *)
let metadataItemFNumberKey: String
@available(OSX 10.9, *)
let metadataItemExposureProgramKey: String
@available(OSX 10.9, *)
let metadataItemExposureTimeStringKey: String
@available(OSX 10.9, *)
let metadataItemHeadlineKey: String
@available(OSX 10.9, *)
let metadataItemInstructionsKey: String
@available(OSX 10.9, *)
let metadataItemCityKey: String
@available(OSX 10.9, *)
let metadataItemStateOrProvinceKey: String
@available(OSX 10.9, *)
let metadataItemCountryKey: String
@available(OSX 10.9, *)
let metadataItemTextContentKey: String
@available(OSX 10.9, *)
let metadataItemAudioSampleRateKey: String
@available(OSX 10.9, *)
let metadataItemAudioChannelCountKey: String
@available(OSX 10.9, *)
let metadataItemTempoKey: String
@available(OSX 10.9, *)
let metadataItemKeySignatureKey: String
@available(OSX 10.9, *)
let metadataItemTimeSignatureKey: String
@available(OSX 10.9, *)
let metadataItemAudioEncodingApplicationKey: String
@available(OSX 10.9, *)
let metadataItemComposerKey: String
@available(OSX 10.9, *)
let metadataItemLyricistKey: String
@available(OSX 10.9, *)
let metadataItemAudioTrackNumberKey: String
@available(OSX 10.9, *)
let metadataItemRecordingDateKey: String
@available(OSX 10.9, *)
let metadataItemMusicalGenreKey: String
@available(OSX 10.9, *)
let metadataItemIsGeneralMIDISequenceKey: String
@available(OSX 10.9, *)
let metadataItemRecordingYearKey: String
@available(OSX 10.9, *)
let metadataItemOrganizationsKey: String
@available(OSX 10.9, *)
let metadataItemLanguagesKey: String
@available(OSX 10.9, *)
let metadataItemRightsKey: String
@available(OSX 10.9, *)
let metadataItemPublishersKey: String
@available(OSX 10.9, *)
let metadataItemContributorsKey: String
@available(OSX 10.9, *)
let metadataItemCoverageKey: String
@available(OSX 10.9, *)
let metadataItemSubjectKey: String
@available(OSX 10.9, *)
let metadataItemThemeKey: String
@available(OSX 10.9, *)
let metadataItemDescriptionKey: String
@available(OSX 10.9, *)
let metadataItemIdentifierKey: String
@available(OSX 10.9, *)
let metadataItemAudiencesKey: String
@available(OSX 10.9, *)
let metadataItemNumberOfPagesKey: String
@available(OSX 10.9, *)
let metadataItemPageWidthKey: String
@available(OSX 10.9, *)
let metadataItemPageHeightKey: String
@available(OSX 10.9, *)
let metadataItemSecurityMethodKey: String
@available(OSX 10.9, *)
let metadataItemCreatorKey: String
@available(OSX 10.9, *)
let metadataItemEncodingApplicationsKey: String
@available(OSX 10.9, *)
let metadataItemDueDateKey: String
@available(OSX 10.9, *)
let metadataItemStarRatingKey: String
@available(OSX 10.9, *)
let metadataItemPhoneNumbersKey: String
@available(OSX 10.9, *)
let metadataItemEmailAddressesKey: String
@available(OSX 10.9, *)
let metadataItemInstantMessageAddressesKey: String
@available(OSX 10.9, *)
let metadataItemKindKey: String
@available(OSX 10.9, *)
let metadataItemRecipientsKey: String
@available(OSX 10.9, *)
let metadataItemFinderCommentKey: String
@available(OSX 10.9, *)
let metadataItemFontsKey: String
@available(OSX 10.9, *)
let metadataItemAppleLoopsRootKeyKey: String
@available(OSX 10.9, *)
let metadataItemAppleLoopsKeyFilterTypeKey: String
@available(OSX 10.9, *)
let metadataItemAppleLoopsLoopModeKey: String
@available(OSX 10.9, *)
let metadataItemAppleLoopDescriptorsKey: String
@available(OSX 10.9, *)
let metadataItemMusicalInstrumentCategoryKey: String
@available(OSX 10.9, *)
let metadataItemMusicalInstrumentNameKey: String
@available(OSX 10.9, *)
let metadataItemCFBundleIdentifierKey: String
@available(OSX 10.9, *)
let metadataItemInformationKey: String
@available(OSX 10.9, *)
let metadataItemDirectorKey: String
@available(OSX 10.9, *)
let metadataItemProducerKey: String
@available(OSX 10.9, *)
let metadataItemGenreKey: String
@available(OSX 10.9, *)
let metadataItemPerformersKey: String
@available(OSX 10.9, *)
let metadataItemOriginalFormatKey: String
@available(OSX 10.9, *)
let metadataItemOriginalSourceKey: String
@available(OSX 10.9, *)
let metadataItemAuthorEmailAddressesKey: String
@available(OSX 10.9, *)
let metadataItemRecipientEmailAddressesKey: String
@available(OSX 10.9, *)
let metadataItemAuthorAddressesKey: String
@available(OSX 10.9, *)
let metadataItemRecipientAddressesKey: String
@available(OSX 10.9, *)
let metadataItemIsLikelyJunkKey: String
@available(OSX 10.9, *)
let metadataItemExecutableArchitecturesKey: String
@available(OSX 10.9, *)
let metadataItemExecutablePlatformKey: String
@available(OSX 10.9, *)
let metadataItemApplicationCategoriesKey: String
@available(OSX 10.9, *)
let metadataItemIsApplicationManagedKey: String
