
var xmlNodeOptionsNone: Int { get }
var xmlNodeIsCDATA: Int { get }
var xmlNodeExpandEmptyElement: Int { get }
var xmlNodeCompactEmptyElement: Int { get }
var xmlNodeUseSingleQuotes: Int { get }
var xmlNodeUseDoubleQuotes: Int { get }
var xmlNodeNeverEscapeContents: Int { get }
var xmlDocumentTidyHTML: Int { get }
var xmlDocumentTidyXML: Int { get }
var xmlDocumentValidate: Int { get }
var xmlNodeLoadExternalEntitiesAlways: Int { get }
var xmlNodeLoadExternalEntitiesSameOriginOnly: Int { get }
var xmlNodeLoadExternalEntitiesNever: Int { get }
var xmlDocumentXInclude: Int { get }
var xmlNodePrettyPrint: Int { get }
var xmlDocumentIncludeContentTypeDeclaration: Int { get }
var xmlNodePreserveNamespaceOrder: Int { get }
var xmlNodePreserveAttributeOrder: Int { get }
var xmlNodePreserveEntities: Int { get }
var xmlNodePreservePrefixes: Int { get }
var xmlNodePreserveCDATA: Int { get }
var xmlNodePreserveWhitespace: Int { get }
var xmlNodePreserveDTD: Int { get }
var xmlNodePreserveCharacterReferences: Int { get }
var xmlNodePromoteSignificantWhitespace: Int { get }
var xmlNodePreserveEmptyElements: Int { get }
var xmlNodePreserveQuotes: Int { get }
var xmlNodePreserveAll: Int { get }
