
@available(OSX 10.7, *)
class IOBluetoothHandsFreeDevice : IOBluetoothHandsFree {
  @available(OSX 10.7, *)
  init!(device: IOBluetoothDevice!, delegate: AnyObject!)
  @available(OSX 10.7, *)
  func dialNumber(aNumber: String!)
  @available(OSX 10.7, *)
  func memoryDial(memoryLocation: Int32)
  @available(OSX 10.7, *)
  func redial()
  @available(OSX 10.7, *)
  func endCall()
  @available(OSX 10.7, *)
  func acceptCall()
  @available(OSX 10.7, *)
  func acceptCallOnPhone()
  @available(OSX 10.7, *)
  func sendDTMF(character: String!)
  @available(OSX 10.7, *)
  func subscriberNumber()
  @available(OSX 10.7, *)
  func currentCallList()
  @available(OSX 10.7, *)
  func releaseHeldCalls()
  @available(OSX 10.7, *)
  func releaseActiveCalls()
  @available(OSX 10.7, *)
  func releaseCall(index: Int32)
  @available(OSX 10.7, *)
  func holdCall()
  @available(OSX 10.7, *)
  func placeAllOthersOnHold(index: Int32)
  @available(OSX 10.7, *)
  func addHeldCall()
  @available(OSX 10.7, *)
  func callTransfer()
  @available(OSX 10.7, *)
  func transferAudioToComputer()
  @available(OSX 10.7, *)
  func transferAudioToPhone()
  @available(OSX 10.7, *)
  func sendSMS(aNumber: String!, message aMessage: String!)
  @available(OSX 10.7, *)
  func sendATCommand(atCommand: String!)
  @available(OSX 10.7, *)
  func sendATCommand(atCommand: String!, timeout: Float, selector: Selector, target: AnyObject!)
  init()
}
protocol IOBluetoothHandsFreeDeviceDelegate : IOBluetoothHandsFreeDelegate {
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, isServiceAvailable: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, isCallActive: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, callSetupMode: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, callHoldState: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, signalStrength: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, isRoaming: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, batteryCharge: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, incomingCallFrom number: String!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, ringAttempt: NSNumber!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, currentCall: [NSObject : AnyObject]!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, subscriberNumber: String!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, incomingSMS sms: [NSObject : AnyObject]!)
  @available(OSX 10.7, *)
  optional func handsFree(device: IOBluetoothHandsFreeDevice!, unhandledResultCode resultCode: String!)
}
