
extension CSSearchableItemAttributeSet {
  var editors: [String]?
  var participants: [String]?
  var projects: [String]?
  var downloadedDate: Date?
  var contentSources: [String]?
  var comment: String?
  var copyright: String?
  var lastUsedDate: Date?
  var contentCreationDate: Date?
  var contentModificationDate: Date?
  var addedDate: Date?
  var duration: Number?
  var contactKeywords: [String]?
  var version: String?
  var codecs: [String]?
  var mediaTypes: [String]?
  var streamable: Number?
  var totalBitRate: Number?
  var videoBitRate: Number?
  var audioBitRate: Number?
  var deliveryType: Number?
  var organizations: [String]?
  var role: String?
  var languages: [String]?
  var rights: String?
  var publishers: [String]?
  var contributors: [String]?
  var coverage: [String]?
  var rating: Number?
  var ratingDescription: String?
  var playCount: Number?
  var information: String?
  var director: String?
  var producer: String?
  var genre: String?
  var performers: [String]?
  var originalFormat: String?
  var originalSource: String?
  var local: Number?
  var contentRating: Number?
  var url: URL?
}
extension CSSearchableItemAttributeSet {
  var audioSampleRate: Number?
  var audioChannelCount: Number?
  var tempo: Number?
  var keySignature: String?
  var timeSignature: String?
  var audioEncodingApplication: String?
  var composer: String?
  var lyricist: String?
  var album: String?
  var artist: String?
  var audioTrackNumber: Number?
  var recordingDate: Date?
  var musicalGenre: String?
  var generalMIDISequence: Number?
  var musicalInstrumentCategory: String?
  var musicalInstrumentName: String?
}
