
@available(tvOS 5.0, *)
let metadataItemFSNameKey: String
@available(tvOS 5.0, *)
let metadataItemDisplayNameKey: String
@available(tvOS 5.0, *)
let metadataItemURLKey: String
@available(tvOS 5.0, *)
let metadataItemPathKey: String
@available(tvOS 5.0, *)
let metadataItemFSSizeKey: String
@available(tvOS 5.0, *)
let metadataItemFSCreationDateKey: String
@available(tvOS 5.0, *)
let metadataItemFSContentChangeDateKey: String
@available(tvOS 8.0, *)
let metadataItemContentTypeKey: String
@available(tvOS 8.0, *)
let metadataItemContentTypeTreeKey: String
@available(tvOS 5.0, *)
let metadataItemIsUbiquitousKey: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemHasUnresolvedConflictsKey: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemDownloadingStatusKey: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemDownloadingStatusNotDownloaded: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemDownloadingStatusDownloaded: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemDownloadingStatusCurrent: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemIsDownloadingKey: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemIsUploadedKey: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemIsUploadingKey: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemPercentDownloadedKey: String
@available(tvOS 5.0, *)
let metadataUbiquitousItemPercentUploadedKey: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemDownloadingErrorKey: String
@available(tvOS 7.0, *)
let metadataUbiquitousItemUploadingErrorKey: String
@available(tvOS 8.0, *)
let metadataUbiquitousItemDownloadRequestedKey: String
@available(tvOS 8.0, *)
let metadataUbiquitousItemIsExternalDocumentKey: String
@available(tvOS 8.0, *)
let metadataUbiquitousItemContainerDisplayNameKey: String
@available(tvOS 8.0, *)
let metadataUbiquitousItemURLInLocalContainerKey: String
